### ISSUE TITLE
Unsafe use of eval

### ISSUE THREAD

**Issue by cristianstaicu** [microServiceBus/microservicebus.node#9]
The eval calls in microServiceBusHost.js and Services/microService.js are potentially dangerous, e.g.:
```js
expression = 'message =' + messageString + ';\n' + varialbesString + routingExpression.value;
eval(expression);
```
I suggest refactoring eval out, use regular expressions to validate the input or use a sanitization package like: 
https://www.npmjs.com/package/eval-sanitizer

**Comment by wmmihaa** [comment]
@cristianstaicu Sorry for late reply. I don't I'll implement this shortly. However I'm probobly making it optional. In the end it's your code, running on your device.

**Comment by wmmihaa** [comment]
I've submitted an issue to your repository: https://github.com/cristianstaicu/eval-sanitizer/issues/2
